#ifndef ACCOUNT_H
#define ACCOUNT_H

#include <string>
#include "user.h"

/**
 * @class Account
 * @brief Represents a user's login credentials and links to their User profile.
 *
 * This class holds the account-specific data (ID, username, hash) and
 * composes a User object which holds the personal profile data (CPF, email, etc.).
 */
class Account {
private:
    std::string id;       // Unique account ID (generated by Validate)
    size_t hash;          // The stored password hash
    std::string username; // The login username
    User user;            // The associated user profile object

public:
    /**
     * @brief Constructor for creating a new Account.
     * @param i_id The unique account ID.
     * @param i_hash The password hash.
     * @param i_username The login username.
     * @param i_user The associated User object.
     */
    Account(const std::string& i_id,
            const size_t& i_hash,
            const std::string& i_username,
            const User& i_user);

    // --- Getters ---

    /**
     * @brief Gets the stored password hash.
     * @return A const reference to the hash.
     */
    const size_t& getHash() const;

    /**
     * @brief Gets the account's unique ID.
     * @return A const reference to the ID string.
     */
    const std::string& getId() const;

    /**
     * @brief Gets the account's username.
     * @return A const reference to the username string.
     */
    const std::string& getUsername() const;

    /**
     * @brief Gets a read-only (const) reference to the associated User object.
     * @return A const reference to the User.
     */
    const User& getUser() const;

    /**
     * @brief Gets a writable (mutable) reference to the associated User object.
     * @return A reference to the User (used for updates, e.g., changing name).
     */
    User& getUser();

    // --- Update Methods ---

    /**
     * @brief Updates the password hash if the current hash is correct.
     * @param current_hash The user's provided current password hash.
     * @param new_hash The new password hash to set.
     * @return true if the password was changed, false otherwise.
     */
    bool change_password(const size_t& current_hash, const size_t& new_hash);

    /**
     * @brief Updates the account's username.
     * @param new_username The new username.
     * @return true (always succeeds).
     */
    bool change_username(const std::string& new_username);
};

#endif